exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "__*.py",
    "**/migrations/**.py",
    "apps.py",
]

line-length = 120
indent-width = 4

target-version = "py313"

[lint]
preview = true

select = ["ALL"]
ignore = ["E721", "D105", "D211", "D212", "G004", "W191", "D206", "D404", "D203", "CPY001", "EM102", "TRY003", "PLR0904", "D205", "TID252", "D100", "D200", "S603", "S404", "S602", "TRY301", "C417", "FA100", "EM101", "PLR2004", "FURB113", "E741", "UP007", "UP045", "T201", "PD901", "ERA001", "FBT003", "N806", "PLR0914"]
extend-select = ["DOC"]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
preview = true

quote-style = "single"
docstring-code-format = true

indent-style = "tab"

skip-magic-trailing-comma = false

line-ending = "auto"

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pydocstyle]
convention = "google"

[lint.pycodestyle]
max-doc-length = 500